version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid # Cambia a tu zona horaria
      - SERVERURL=auto # Cambia si tienes una URL fija
      - SERVERPORT=51820 # El puerto puede ser cambiado
      - PEERS=3 # Número de clientes
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0/24 # Define la subred interna de WireGuard
    volumes:
      - /home/ubuntu/Wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
